In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 전체 게임 데이터에서 LCK 데이터 추출
#match_data = pd.read_csv('2021_LoL_esports_match_data_from_OraclesElixir_20210526.csv')
#match_data = match_data[match_data['league']=='LCK']
#match_data

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
1548,ESPORTSTMNT01/1690520,complete,http://matchhistory.na.leagueoflegends.com/en/...,LCK,2021,Spring,0,1/13/2021 7:00,1,11.01,...,130.0,1548.0,1464.0,-8.0,3.0,1.0,0.0,0.0,0.0,4.0
1549,ESPORTSTMNT01/1690520,complete,http://matchhistory.na.leagueoflegends.com/en/...,LCK,2021,Spring,0,1/13/2021 7:00,1,11.01,...,110.0,903.0,1005.0,12.0,1.0,3.0,1.0,0.0,0.0,0.0
1550,ESPORTSTMNT01/1690520,complete,http://matchhistory.na.leagueoflegends.com/en/...,LCK,2021,Spring,0,1/13/2021 7:00,1,11.01,...,167.0,-261.0,-225.0,-20.0,1.0,1.0,0.0,0.0,0.0,0.0
1551,ESPORTSTMNT01/1690520,complete,http://matchhistory.na.leagueoflegends.com/en/...,LCK,2021,Spring,0,1/13/2021 7:00,1,11.01,...,145.0,-44.0,-205.0,-4.0,0.0,2.0,0.0,0.0,1.0,0.0
1552,ESPORTSTMNT01/1690520,complete,http://matchhistory.na.leagueoflegends.com/en/...,LCK,2021,Spring,0,1/13/2021 7:00,1,11.01,...,16.0,-55.0,-258.0,6.0,1.0,0.0,0.0,1.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,ESPORTSTMNT03/1816183,complete,http://matchhistory.na.leagueoflegends.com/en/...,LCK,2021,Spring,1,4/10/2021 10:29,3,11.06,...,152.0,-164.0,-604.0,-19.0,1.0,0.0,1.0,1.0,0.0,1.0
59996,ESPORTSTMNT03/1816183,complete,http://matchhistory.na.leagueoflegends.com/en/...,LCK,2021,Spring,1,4/10/2021 10:29,3,11.06,...,128.0,-875.0,-730.0,-105.0,0.0,0.0,0.0,0.0,0.0,0.0
59997,ESPORTSTMNT03/1816183,complete,http://matchhistory.na.leagueoflegends.com/en/...,LCK,2021,Spring,1,4/10/2021 10:29,3,11.06,...,15.0,1585.0,1038.0,95.0,0.0,0.0,0.0,0.0,0.0,0.0
59998,ESPORTSTMNT03/1816183,complete,http://matchhistory.na.leagueoflegends.com/en/...,LCK,2021,Spring,1,4/10/2021 10:29,3,11.06,...,541.0,-2465.0,-879.0,-8.0,2.0,1.0,2.0,2.0,2.0,2.0
59999,ESPORTSTMNT03/1816183,complete,http://matchhistory.na.leagueoflegends.com/en/...,LCK,2021,Spring,1,4/10/2021 10:29,3,11.06,...,533.0,2465.0,879.0,8.0,2.0,2.0,2.0,2.0,1.0,2.0

In [3]:
# 전체 플레이어 데이터에서 원딜 데이터 추출
player_data = pd.read_csv('LCK 2021 Spring - Player Stats - OraclesElixir.csv')
player_data = player_data[player_data['Pos']=='Top']

# 편의를 위해 부수적인 기호 삭제
for col in player_data.columns:
    if isinstance(player_data[col].iloc[0], str):
        player_data[col] = player_data[col].map(lambda x: x.replace('%', ''))

# 전부 소수(float) 형으로 변경
for col in player_data.columns[3:]:
    player_data[col] = pd.to_numeric(player_data[col], downcast = 'float')
    
# K, D, A 평균으로 변경
for col in ['K', 'D', 'A']:
    player_data[col] = player_data[col]/player_data['GP']
        
player_data

,Player,Team,Pos,GP,W%,CTR%,K,D,A,KDA,...,XPD10,CSD10,CSPM,CS%P15,DPM,DMG%,EGPM,GOLD%,WPM,WCPM
59,Canna,T1,Top,25.0,60.0,52.0,2.800000,2.840000,5.920000,3.1,...,4.0,-0.9,8.2,24.799999,435.0,23.000000,265.0,22.299999,0.40,0.20
60,Doran,KT Rolster,Top,45.0,40.0,58.0,1.911111,2.666667,4.777778,2.5,...,29.0,3.5,8.5,24.500000,483.0,27.799999,254.0,22.900000,0.51,0.23
61,DuDu,Hanwha Life Esports,Top,8.0,13.0,25.0,2.750000,2.500000,2.875000,2.3,...,100.0,3.5,8.4,26.400000,497.0,26.400000,255.0,24.400000,0.36,0.21
62,Hoya,Fredit BRION,Top,39.0,31.0,44.0,1.410256,2.564103,4.000000,2.1,...,-77.0,-7.3,7.3,20.500000,350.0,22.600000,204.0,20.100000,0.50,0.20
63,Khan,DWG KIA,Top,43.0,77.0,56.0,1.953488,2.255814,7.139535,4.0,...,-27.0,-0.3,7.5,21.100000,502.0,23.200001,243.0,19.799999,0.43,0.21
64,Kiin,Afreeca Freecs,Top,42.0,38.0,57.0,2.023809,2.952381,5.071429,2.4,...,177.0,3.5,8.0,24.100000,489.0,26.799999,244.0,22.200001,0.40,0.23
65,Kingen,DRX,Top,47.0,45.0,66.0,1.936170,2.574468,5.319149,2.8,...,56.0,5.3,7.7,22.000000,466.0,25.299999,248.0,22.299999,0.39,0.19
66,Morgan,Hanwha Life Esports,Top,36.0,69.0,42.0,2.138889,2.083333,6.500000,4.1,...,-115.0,-5.5,7.6,21.799999,416.0,19.700001,237.0,19.700001,0.40,0.26
67,Rascal,Gen.G,Top,44.0,66.0,43.0,2.568182,2.409091,4.795455,3.1,...,42.0,2.5,8.7,25.799999,396.0,22.900000,279.0,23.400000,0.34,0.26
68,Rich,Nongshim RedForce,Top,42.0,43.0,57.0,2.000000,3.023809,4.809524,2.3,...,-206.0,-6.4,7.2,20.600000,482.0,25.900000,218.0,20.200001,0.35,0.25
69,Summit,Liiv SANDBOX,Top,40.0,38.0,40.0,2.600000,3.275000,4.950000,2.3,...,38.0,1.9,8.3,25.299999,490.0,26.900000,259.0,23.100000,0.46,0.26
70,Zeus,T1,Top,19.0,63.0,21.0,2.210526,2.473684,5.473684,3.1,...,70.0,1.3,7.6,22.200001,421.0,22.500000,240.0,20.600000,0.33,0.18

In [4]:
# 팀별 종합 데이터
team_data = pd.read_csv('LCK 2021 Spring - Team Stats - OraclesElixir.csv')

# 편의를 위해 부수적인 기호 삭제
for col in team_data.columns:
    if isinstance(team_data[col].iloc[0], str):
        team_data[col] = team_data[col].map(lambda x: x.replace('%', ''))

# 전부 소수(float)형으로 변경
for col in team_data.columns[1:]:
    team_data[col] = pd.to_numeric(team_data[col], downcast = 'float')
    
team_data

,Team,GP,W,L,AGT,K,D,KD,CKPM,GPR,...,FD%,DRG%,ELD%,FBN%,BN%,LNE%,JNG%,WPM,CWPM,WCPM
0,Afreeca Freecs,42.0,16.0,26.0,33.500000,509.0,579.0,0.88,0.77,0.15,...,55.0,54.0,29.0,40.0,41.0,49.400002,48.500000,3.73,1.52,1.87
1,DRX,47.0,21.0,26.0,33.700001,518.0,599.0,0.86,0.71,-0.34,...,32.0,41.0,50.0,49.0,48.0,49.900002,50.500000,3.73,1.34,1.75
2,DWG KIA,43.0,33.0,10.0,33.299999,647.0,486.0,1.33,0.79,0.82,...,51.0,65.0,60.0,70.0,74.0,49.500000,56.299999,3.81,1.48,1.78
3,Fredit BRION,39.0,12.0,27.0,32.799999,361.0,469.0,0.77,0.65,-1.10,...,54.0,46.0,40.0,28.0,33.0,49.099998,46.500000,3.97,1.55,1.94
4,Gen.G,44.0,29.0,15.0,32.299999,547.0,435.0,1.26,0.69,0.69,...,68.0,56.0,50.0,73.0,72.0,51.099998,51.500000,4.03,1.57,1.98
5,Hanwha Life Esports,44.0,26.0,18.0,31.900000,614.0,535.0,1.15,0.82,0.29,...,55.0,58.0,60.0,50.0,53.0,51.000000,50.400002,3.68,1.47,1.95
6,KT Rolster,45.0,18.0,27.0,34.299999,500.0,574.0,0.87,0.69,-0.51,...,31.0,37.0,45.0,38.0,43.0,50.000000,48.500000,3.97,1.48,1.83
7,Liiv SANDBOX,40.0,15.0,25.0,32.599998,480.0,553.0,0.87,0.79,-0.29,...,45.0,44.0,43.0,33.0,32.0,50.200001,45.700001,3.68,1.54,1.88
8,Nongshim RedForce,42.0,18.0,24.0,32.200001,476.0,551.0,0.86,0.76,-0.60,...,52.0,50.0,75.0,45.0,44.0,49.299999,49.400002,3.68,1.30,1.78
9,T1,44.0,27.0,17.0,32.700001,612.0,494.0,1.24,0.77,0.81,...,59.0,52.0,60.0,55.0,58.0,50.500000,51.799999,3.67,1.41,1.72

In [5]:
player_data['DMG%/KP'] = player_data['DMG%']
player_data['DMG%/KP'] /= player_data['KP']
player_data = player_data.sort_values('DMG%/KP', ascending=False)
player_data

,Player,Team,Pos,GP,W%,CTR%,K,D,A,KDA,...,CSD10,CSPM,CS%P15,DPM,DMG%,EGPM,GOLD%,WPM,WCPM,DMG%/KP
61,DuDu,Hanwha Life Esports,Top,8.0,13.0,25.0,2.750000,2.500000,2.875000,2.3,...,3.5,8.4,26.400000,497.0,26.400000,255.0,24.400000,0.36,0.21,0.474820
60,Doran,KT Rolster,Top,45.0,40.0,58.0,1.911111,2.666667,4.777778,2.5,...,3.5,8.5,24.500000,483.0,27.799999,254.0,22.900000,0.51,0.23,0.461794
64,Kiin,Afreeca Freecs,Top,42.0,38.0,57.0,2.023809,2.952381,5.071429,2.4,...,3.5,8.0,24.100000,489.0,26.799999,244.0,22.200001,0.40,0.23,0.458120
68,Rich,Nongshim RedForce,Top,42.0,43.0,57.0,2.000000,3.023809,4.809524,2.3,...,-6.4,7.2,20.600000,482.0,25.900000,218.0,20.200001,0.35,0.25,0.430948
69,Summit,Liiv SANDBOX,Top,40.0,38.0,40.0,2.600000,3.275000,4.950000,2.3,...,1.9,8.3,25.299999,490.0,26.900000,259.0,23.100000,0.46,0.26,0.427663
62,Hoya,Fredit BRION,Top,39.0,31.0,44.0,1.410256,2.564103,4.000000,2.1,...,-7.3,7.3,20.500000,350.0,22.600000,204.0,20.100000,0.50,0.20,0.386986
67,Rascal,Gen.G,Top,44.0,66.0,43.0,2.568182,2.409091,4.795455,3.1,...,2.5,8.7,25.799999,396.0,22.900000,279.0,23.400000,0.34,0.26,0.386824
59,Canna,T1,Top,25.0,60.0,52.0,2.800000,2.840000,5.920000,3.1,...,-0.9,8.2,24.799999,435.0,23.000000,265.0,22.299999,0.40,0.20,0.385906
65,Kingen,DRX,Top,47.0,45.0,66.0,1.936170,2.574468,5.319149,2.8,...,5.3,7.7,22.000000,466.0,25.299999,248.0,22.299999,0.39,0.19,0.384498
63,Khan,DWG KIA,Top,43.0,77.0,56.0,1.953488,2.255814,7.139535,4.0,...,-0.3,7.5,21.100000,502.0,23.200001,243.0,19.799999,0.43,0.21,0.384106
70,Zeus,T1,Top,19.0,63.0,21.0,2.210526,2.473684,5.473684,3.1,...,1.3,7.6,22.200001,421.0,22.500000,240.0,20.600000,0.33,0.18,0.379427
66,Morgan,Hanwha Life Esports,Top,36.0,69.0,42.0,2.138889,2.083333,6.500000,4.1,...,-5.5,7.6,21.799999,416.0,19.700001,237.0,19.700001,0.40,0.26,0.337907

In [6]:
spring_rank = ['DWG KIA', 'Gen.G', 'Hanwha Life Esports', 'T1', 'DRX', 'Nongshim RedForce', 'KT Rolster', 'Afreeca Freecs', 'Liiv SANDBOX', 'Fredit BRION']

player_data.Team = pd.Categorical(player_data.Team, categories=spring_rank, ordered = True)
player_data.sort_values('Team', inplace=True)

spring_rank_list = [spring_rank.index(x)+1 for x in player_data.Team]
player_data['Spring_Rank'] = spring_rank_list

player_data

,Player,Team,Pos,GP,W%,CTR%,K,D,A,KDA,...,CSPM,CS%P15,DPM,DMG%,EGPM,GOLD%,WPM,WCPM,DMG%/KP,Spring_Rank
63,Khan,DWG KIA,Top,43.0,77.0,56.0,1.953488,2.255814,7.139535,4.0,...,7.5,21.100000,502.0,23.200001,243.0,19.799999,0.43,0.21,0.384106,1
67,Rascal,Gen.G,Top,44.0,66.0,43.0,2.568182,2.409091,4.795455,3.1,...,8.7,25.799999,396.0,22.900000,279.0,23.400000,0.34,0.26,0.386824,2
61,DuDu,Hanwha Life Esports,Top,8.0,13.0,25.0,2.750000,2.500000,2.875000,2.3,...,8.4,26.400000,497.0,26.400000,255.0,24.400000,0.36,0.21,0.474820,3
66,Morgan,Hanwha Life Esports,Top,36.0,69.0,42.0,2.138889,2.083333,6.500000,4.1,...,7.6,21.799999,416.0,19.700001,237.0,19.700001,0.40,0.26,0.337907,3
59,Canna,T1,Top,25.0,60.0,52.0,2.800000,2.840000,5.920000,3.1,...,8.2,24.799999,435.0,23.000000,265.0,22.299999,0.40,0.20,0.385906,4
70,Zeus,T1,Top,19.0,63.0,21.0,2.210526,2.473684,5.473684,3.1,...,7.6,22.200001,421.0,22.500000,240.0,20.600000,0.33,0.18,0.379427,4
65,Kingen,DRX,Top,47.0,45.0,66.0,1.936170,2.574468,5.319149,2.8,...,7.7,22.000000,466.0,25.299999,248.0,22.299999,0.39,0.19,0.384498,5
68,Rich,Nongshim RedForce,Top,42.0,43.0,57.0,2.000000,3.023809,4.809524,2.3,...,7.2,20.600000,482.0,25.900000,218.0,20.200001,0.35,0.25,0.430948,6
60,Doran,KT Rolster,Top,45.0,40.0,58.0,1.911111,2.666667,4.777778,2.5,...,8.5,24.500000,483.0,27.799999,254.0,22.900000,0.51,0.23,0.461794,7
64,Kiin,Afreeca Freecs,Top,42.0,38.0,57.0,2.023809,2.952381,5.071429,2.4,...,8.0,24.100000,489.0,26.799999,244.0,22.200001,0.40,0.23,0.458120,8
69,Summit,Liiv SANDBOX,Top,40.0,38.0,40.0,2.600000,3.275000,4.950000,2.3,...,8.3,25.299999,490.0,26.900000,259.0,23.100000,0.46,0.26,0.427663,9
62,Hoya,Fredit BRION,Top,39.0,31.0,44.0,1.410256,2.564103,4.000000,2.1,...,7.3,20.500000,350.0,22.600000,204.0,20.100000,0.50,0.20,0.386986,10

In [7]:
# 스프링 시즌 등수와 상관 계수가 0.8이상인 지표 (3점)
rank_1_columns = player_data.corr()[player_data.corr()['Spring_Rank']<=-0.8].index
rank_1_columns = [item for item in rank_1_columns]

# 스프링 시즌 등수와 상관 계수가 0.6이상인 지표 (2점)
rank_2_columns = player_data.corr()[player_data.corr()['Spring_Rank']<=-0.6].index
rank_2_columns = [item for item in rank_2_columns if item not in rank_1_columns]

# 스프링 시즌 등수와 상관 계수가 0.4이상인 지표 (1점)
rank_3_columns = player_data.corr()[player_data.corr()['Spring_Rank']<=-0.4].index
rank_3_columns = [item for item in rank_3_columns if item not in rank_2_columns]
rank_3_columns = [item for item in rank_3_columns if item not in rank_1_columns]

# 선수별 점수 저장 DataFrame 만들기
tmp_list = np.array([0] * player_data['Player'].count())
ADC_score = DataFrame(data=tmp_list, index = player_data.Player, columns = ['Score'])

In [8]:
copied_player_data = player_data
for column in rank_1_columns:
    copied_player_data.sort_values(column, inplace=True) # 해당 지표로 정렬 역순
    copied_player_data['Rank'] = np.arange(copied_player_data['Player'].count()) # 순위 매기기
    ADC_score = ADC_score.add(DataFrame(data=Series(list(copied_player_data['Rank']*3), index=list(copied_player_data['Player'])),index = player_data.Player, columns = ['Score']))

In [9]:
for column in rank_2_columns:
    copied_player_data.sort_values(column, inplace=True) # 해당 지표로 정렬 역순
    copied_player_data['Rank'] = np.arange(copied_player_data['Player'].count()) # 순위 매기기
    ADC_score = ADC_score.add(DataFrame(data=Series(list(copied_player_data['Rank']*2), index=list(copied_player_data['Player'])),index = player_data.Player, columns = ['Score']))

In [10]:
for column in rank_3_columns:
    copied_player_data.sort_values(column, inplace=True) # 해당 지표로 정렬 역순
    copied_player_data['Rank'] = np.arange(copied_player_data['Player'].count()) # 순위 매기기
    ADC_score = ADC_score.add(DataFrame(data=Series(list(copied_player_data['Rank']), index=list(copied_player_data['Player'])),index = player_data.Player, columns = ['Score']))

In [11]:
ADC_score.sort_values('Score', ascending=False)

        Score
Player
Canna      53
Morgan     50
Khan       49
Rascal     45
Zeus       44
Kingen     33
Summit     31
Kiin       27
Doran      24
DuDu       20
Rich       18
Hoya        2